### ISSUE TITLE
NPC Spawn Event not returning position.

### ISSUE THREAD

**Issue by GitFlip** [Deathmax/TerrariaAPI-Server#47]
I am making a TShock plugin and I am using the NPCSpawn hook. I can correctly get the NPC, but it's position (x,y) is always (0,0). Is this a bug or intended?

https://github.com/Deathmax/TerrariaAPI-Server/blob/d446a8288a5d7984f4298a507a64249865259472/TerrariaApi.Server/HookManager.cs#L632

public override void Initialize()
{
    .....
    ServerApi.Hooks.NpcSpawn.Register(this, OnNpcSpawn, 5);
    ....
}
....
public void OnNpcSpawn(NpcSpawnEventArgs args)
{
    NPC npc= args.Npc;
    Log.ConsoleInfo("NPC " + npc.type + " Spawned at " + npc.position.X + ", " + npc.position.Y);
}

NPC 61 Spawned at 0, 0
NPC 69 Spawned at 0, 0

**Comment by Olink** [comment]
3ed336cb3fd50dbf796d9478e0a8d3c123ec92d9 solves this issue
